### ISSUE TITLE
Add more examples of how to use the provider

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-confluent#1]
We don't have any real resource docs so we should create more examples of how to use the provider

These examples should be added to the CI job so we don't break them and they are kept up to date﻿

**Comment by aviflax** [comment]
Yes please! For example, the provider requires a username. I’m looking at my user account in the Confluent Cloud Web admin, and I see name, email, status, and principal — and it’s not clear which field is my “username”.

Examples would be very helpful!

**Comment by stack72** [comment]
Closing this out as we have CI running for this provider with some examples now
