### ISSUE TITLE
Using Confluent's official Terraform provider

### ISSUE THREAD

**Issue by raytung** [pulumi/pulumi-confluent#11]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hey Pulumi :wave: 

It looks like Confluent has open sourced their official Terraform provider https://github.com/confluentinc/terraform-provider-confluentcloud. From a glance, it doesn't look like it's at feature parity with https://github.com/Mongey/terraform-provider-confluentcloud/ yet, but thought I should create this feature request to see if it makes sense to switch.

Thanks!

### Affected area/feature

Terraform provider

**Comment by mohitreddy1996** [comment]
Any updates on this yet? Thanks!

**Comment by treykasada** [comment]
Confluent's official Terraform Provider still lacks support for Cluster API Keys, Schema Registries, and Connectors. Based on some comments they left in their issue tracker, it looks like Cluster API Key support should be coming within the next month or so, however Schema Registry and Connector support is not yet roadmapped.

Feature parity doesn't seem like it's going to happen anytime soon, unfortunately. 😢

**Comment by treykasada** [comment]
@stack72 I know it wouldn't be the most palatable solution, but is there any appetite for creating a _separate_ Pulumi Provider for Confluent's official Terraform Provider?
We could optionally deprecate _this_ Provider to guide people towards the new Provider while also keeping this one around until the Confluent official one reaches feature parity.

I mainly ask because:
- It's not clear how long it will take for the official Confluent Terraform Provider to reach feature parity (or even _if_ it will)
- My team and I continue to run into strange bugs and behaviours in both the existing Confluent and Kafka Pulumi Providers, and the underlying Terraform Providers overall just don't feel like particularly stable foundations

**Comment by ConfluentSpencer** [comment]
Hey @treykasada , you are correct that API Keys resource will be added by the end of the month in the official Confluent Cloud Terraform Provider. Connectors, Cluster Linking, KSQL and Schema Registry are a bit farther out but we do have plans to add support for all of those resources in the future. I will start a discussion with the Pulumi team about how we can best handle this situation for our shared Confluent and Pulumi customers.

**Comment by rafaribe** [comment]
What if you create a separate provider just like with `azure` and `azure-native`?

**Comment by rafaribe** [comment]
What if you create a separate provider just like with `azure` and `azure-native`? @ConfluentSpencer @stack72

**Comment by stack72** [comment]
Hi all

I am going to close this issue out - we have made the "official" Confluent Cloud provider now available in the Pulumi - ecosystem

[pulumi/pulumi-confluentcloud](https://github.com/pulumi/pulumi-confluentcloud)

You can find the packages available at:

[npmjs.com/package/@pulumi/confluentcloud](https://www.npmjs.com/package/@pulumi/confluentcloud)
[pypi.org/project/pulumi-confluentcloud](https://pypi.org/project/pulumi-confluentcloud/)
[nuget.org/packages/Pulumi.ConfluentCloud](https://www.nuget.org/packages/Pulumi.ConfluentCloud)

Unfortunately, there's no direct migration story between providers but I suggest you can use import

[pulumi.com/docs/guides/adopting/import](https://www.pulumi.com/docs/guides/adopting/import/)

You can use these providers in combination with each other to get all the coverage of the areas

Paul
