### ISSUE TITLE
Unable to connect to Confluent using Pulumi

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-confluent#41]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently, logged in to Confluent using SSO and hence our username/password are not working to login to confluent through Pulumi.  Tried creating an API key too (pair of key and secret) and used them as username and password and still getting : 
```
error: 1 error occurred:
* login: Invalid username or password. 
```

Using an organization access token.

### Affected area/feature
Pulumi-Service

**Comment by lukehoban** [comment]
My understanding of things here.

This provider is a bridged Terraform provider based on github.com/Mongey/terraform-provider-confluentcloud.

That Terraform provider does not support username/password or API Key.  See for example https://github.com/Mongey/terraform-provider-confluentcloud/issues/59.  This is the most requested ask in that provider.

Unfortunately - it appears fixing that issue itself is blocked on a limitation in the underlying Go SDK that that provider uses - tracked in https://github.com/cgroschupp/go-client-confluent-cloud/issues/13.  And that issue appears to require a transition to a fundamentally new version of the underlying Confluent v2 API.

There is a newer more official Confluent Terraform provider at https://github.com/confluentinc/terraform-provider-confluent.  That provider does support API Keys (https://registry.terraform.io/providers/confluentinc/confluent/latest/docs#example-usage).  We will be looking to enable that provider to be available in Pulumi as well - which may be the only available path to addressing this need given the blocking issues in upstream dependencies of the existing provider noted above.

**Comment by stack72** [comment]
Hi all

I am going to close this issue out - we have made the "official" Confluent Cloud provider now available in the Pulumi - ecosystem

https://github.com/pulumi/pulumi-confluentcloud

You can find the packages available at:

https://www.npmjs.com/package/@pulumi/confluentcloud
https://pypi.org/project/pulumi-confluentcloud/
https://www.nuget.org/packages/Pulumi.ConfluentCloud

Unfortunately, there's no direct migration story between providers but I suggest you can use import

https://www.pulumi.com/docs/guides/adopting/import/
