### ISSUE TITLE
Clearly mark this repo as deprecated

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-confluent#51]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This repo is deprecated in favor of https://github.com/pulumi/pulumi-confluentcloud. We should clearly indicate this in the README for this repo and consider archiving it as well if we do not plan to offer future updates.

**Comment by mnlumi** [comment]
https://github.com/pulumi/pulumi-confluent/pull/62

**Comment by mnlumi** [comment]
Closing as completed per #62
